/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
  addArgsEnhancer,
  clearDecorators,
} from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';

import { argsEnhancers } from '@storybook/addon-actions/dist/modern/preset/addArgs';

import { decorators, parameters } from './preview';

if (decorators) {
  if (__DEV__) {
    // stops the warning from showing in the UI
    clearDecorators();
  }
  decorators.forEach((decorator: any) => addDecorator(decorator));
}

if (parameters) {
  addParameters(parameters);
}

try {
  argsEnhancers.forEach((enhancer: any) => addArgsEnhancer(enhancer));
} catch {}

const getStories = () => {
  return [
    require('../src/screens/Onboarding/OnboardingScreen.stories'),
    require('../src/screens/Onboarding/TargetSelectionScreen.stories'),
    require('../src/screens/Vault/VaultScreen.stories'),
    require('../src/components/ui/Button.stories'),
  ];
};

configure(getStories, module, false);
